# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/product/product_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/product/product_event.proto\x12\rproduct.event\"P\n\x18OnInventoryDeductSuccess\x12\x0f\n\x07OrderId\x18\x01 \x01(\x03\x12#\n\x03Sku\x18\x02 \x03(\x0b\x32\x16.product.event.SkuInfo\"I\n\x07SkuInfo\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x10\n\x08Quantity\x18\x02 \x01(\r\x12\r\n\x05Stock\x18\x03 \x01(\r\x12\x11\n\tThreshold\x18\x04 \x01(\rB!Z\x1f./internal/domain/event/productb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product.product_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037./internal/domain/event/product'
  _globals['_ONINVENTORYDEDUCTSUCCESS']._serialized_start=52
  _globals['_ONINVENTORYDEDUCTSUCCESS']._serialized_end=132
  _globals['_SKUINFO']._serialized_start=134
  _globals['_SKUINFO']._serialized_end=207
# @@protoc_insertion_point(module_scope)
